# Usar una imagen base ligera de Python
FROM python:3.11-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos necesarios
COPY requirements-front.txt .
COPY chat.py .

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements-front.txt

# Exponer el puerto 8080
EXPOSE 8080

# Comando para ejecutar Streamlit en el puerto 8080
CMD ["streamlit", "run", "chat.py", "--server.port=8080", "--server.address=0.0.0.0"]
